// src/richtext/adapter/components/toolbar/ScriptFormats.tsx
import { useProsemirror } from "@/richtext/adapter/hooks/useProsemirror";
import { useEditorState } from "@/richtext/adapter/hooks/useEditorState";

export const ScriptFormats = () => {
  const { activeEditor: editor } = useProsemirror();

  const editorState = useEditorState({
    editor,
    selector: (editor) => {
      return {
        marks: {
          subscript: editor.isActive("subscript"),
          superscript: editor.isActive("superscript"),
        },
      };
    },
  });

  if (!editor || !editorState) return null;
  
  return (
    <div style={{ display: "flex", flexDirection: "row", gap: 4 }}>
      <button
        onClick={() => editor.chain().focus().toggleSuperscript().run()}
        style={{
          backgroundColor: editorState?.marks.superscript ? "red" : "",
        }}
        title="Superscript"
      >
        Super
      </button>
      <button
        onClick={() => editor.chain().focus().toggleSubscript().run()}
        style={{ backgroundColor: editorState?.marks.subscript ? "red" : "" }}
        title="Subscript"
      >
        Sub
      </button>
    </div>
  );
};

// src/lib/richtext/adapter/components/toolbar/ScriptFormats.svelte
<script lang="ts">
	import { getRichtextContext } from '../../contexts/richtextContext.svelte';

	const richtextContext = getRichtextContext();
</script>

<div class="container">
	<button
		onclick={() => richtextContext.activeEditor.editor?.chain().focus().toggleSuperscript().run()}
		class:selected={richtextContext.activeEditor.editor?.isActive('subscript')}
		title="Superscript"
	>
		Super
	</button>
	<button
		onclick={() => richtextContext.activeEditor.editor?.chain().focus().toggleSubscript().run()}
		class:selected={richtextContext.activeEditor.editor?.isActive('superscript')}
		title="Subscript"
	>
		Sub
	</button>
</div>

<style>
	.container {
		display: flex;
		flex-direction: row;
		flex-wrap: wrap;
		gap: 4px;
	}

	.selected {
		background-color: red;
	}
</style>
