// src/richtext/adapter/components/toolbar/TextDirectionFormats.tsx
import type { Editor } from "@/richtext/core/Editor";
import type { ProsemirrorState } from "./ProsemirrorToolbar";

export const TextDirectionFormats = ({
  editor,
  editorState,
}: {
  editor: Editor;
  editorState: ProsemirrorState;
}) => {
  return (
    <div style={{ display: "flex", flexDirection: "row", gap: 4 }}>
      <button
        onClick={() => editor.commands.setTextDirection("ltr")}
        style={{ backgroundColor: editorState?.direction.ltr ? "red" : "" }}
        title="Left to Right"
      >
        LTR{" "}
      </button>
      <button
        onClick={() => editor.commands.setTextDirection("rtl")}
        style={{ backgroundColor: editorState?.direction.rtl ? "red" : "" }}
        title="Right to Left"
      >
        RTL
      </button>
    </div>
  );
};

// src/lib/richtext/adapter/components/toolbar/TextDirectionFormats.svelte
<script lang="ts">
	import { getRichtextContext } from '../../contexts/richtextContext.svelte';

	const richtextContext = getRichtextContext();
	const editor = $derived(richtextContext.activeEditor.editor);
</script>

<div class="container">
	<button
		onclick={() => editor?.commands.setTextDirection('ltr')}
		class:selected={editor?.isActive({ dir: 'ltr' })}
		title="Left to Right"
	>
		LTR
	</button>
	<button
		onclick={() => editor?.commands.setTextDirection('rtl')}
		class:selected={editor?.isActive({ dir: 'rtl' })}
		title="Right to Left"
	>
		RTL
	</button>
</div>

<style>
	.container {
		display: flex;
		flex-direction: row;
		flex-wrap: wrap;
		gap: 4px;
	}

	.selected {
		background-color: red;
	}
</style>
