// src/components/blocks/text/TextBlock.tsx
import type { TextBlockEntity } from "@/entities/template";
import { ProsemirrorEditor } from "@/richtext/adapter/components/ProsemirrorEditor";
import { ProsemirrorPreview } from "@/richtext/adapter/components/ProsemirrorPreview";
import type { Editor } from "@/richtext/core/Editor";
import { useDebouncedCallback } from "@/hooks/useDebouncedCallback";
import { useCanvasStore } from "@/stores/useCanvasStore";
import { useUIStore } from "@/stores/useUIStore";
import { UpdateBlockCommand } from "@/commands/blocks/UpdateBlockCommand";
import { historyService } from "@/history/services/historyService";
import { generateId } from "@/utils/generateId";
import { buildTextExtensions } from "@/richtext/adapter/utils/buildExtensions";

interface TextBlockProps {
  block: TextBlockEntity;
}

export const TextBlock: React.FC<TextBlockProps> = ({ block }) => {
  const selectedId = useUIStore((store) => store.selectedId);
  const template = useCanvasStore((store) => store.template);

  const handleUpdate = useDebouncedCallback((editor: Editor) => {
    const state = useCanvasStore.getState();
    const { getTemplate, setTemplate, getBlockCoordinates } = state;

    const blockCoordinates = getBlockCoordinates(block.id);
    if (blockCoordinates === null) return;

    const command = new UpdateBlockCommand({
      ...blockCoordinates,
      getTemplate,
      setTemplate,
      updates: {
        content: {
          html: editor.getHTML(),
          json: editor.getJSON(),
        },
      },
    });
    historyService.executeCommand(command, {
      id: generateId(),
      type: "block.update",
      timestamp: Date.now(),
    });
  }, 300);

  if (!template) return null;

  return (
    <>
      {selectedId === block.id ? (
        <ProsemirrorEditor
          content={block.content.json}
          extensions={buildTextExtensions(template.settings)}
          onUpdate={handleUpdate}
        />
      ) : (
        <ProsemirrorPreview content={block.content.html} />
      )}
    </>
  );
};

// src/lib/template/nodes/blocks/text/TextBlock.svelte
<script lang="ts">
	import { UpdateBlockCommand } from '$lib/commands/blocks/UpdateBlockCommand';
	import { historyService } from '$lib/commands/history/HistoryService.svelte';
	import ProsemirrorEditor from '$lib/richtext/adapter/components/RichtextEditor.svelte';
	import ProsemirrorPreview from '$lib/richtext/adapter/components/RichtextPreview.svelte';
	import { buildTextExtensions } from '$lib/richtext/adapter/utils/buildExtensions';
	import type { Editor } from '$lib/richtext/core/Editor';
	import { getTemplateContext } from '$lib/template/contexts/templateContext.svelte';
	import { getUIContext } from '$lib/template/contexts/uiContext.svelte';
	import { type TextBlockEntity } from '$lib/template/types';
	import { debounce } from '$lib/template/utils/debounce';

	interface Props {
		entity: TextBlockEntity;
	}
	const { entity, ...props }: Props = $props();
	const uiContext = getUIContext();
	const templateContext = getTemplateContext();

	const handleUpdate = debounce((editor: Editor) => {
		const coordinates = templateContext.getBlockCoordinates(entity.id);
		if (!coordinates) return;
		const command = new UpdateBlockCommand({
			store: templateContext,
			coordinates,
			updates: {
				content: {
					html: editor.getHTML(),
					json: editor.getJSON()
				}
			}
		});
		historyService.executeCommand(command, {
			type: 'block.update'
		});
	}, 300);
</script>

<div {...props}>
	{#if uiContext.selectedId === entity.id}
		<ProsemirrorEditor
			content={entity.content.json}
			extensions={buildTextExtensions()}
			onUpdate={handleUpdate}
		/>
	{:else}
		<ProsemirrorPreview content={entity.content.html} />
	{/if}
</div>
