// src/lib/template/nodes/blocks/button/ButtonBlock.svelte
<script lang="ts">
	import { UpdateBlockCommand } from '$lib/commands/blocks/UpdateBlockCommand';
	import { historyService } from '$lib/commands/history/HistoryService.svelte';
	import ProsemirrorEditor from '$lib/richtext/adapter/components/RichtextEditor.svelte';
	import ProsemirrorPreview from '$lib/richtext/adapter/components/RichtextPreview.svelte';
	import { buildButtonExtensions } from '$lib/richtext/adapter/utils/buildExtensions';
	import type { Editor } from '$lib/richtext/core/Editor';
	import { getTemplateContext } from '$lib/template/contexts/templateContext.svelte';
	import { getUIContext } from '$lib/template/contexts/uiContext.svelte';
	import { type ButtonBlockEntity } from '$lib/template/types';
	import { stringifyCssObject } from '$lib/template/utils/stringifyCssObject';
	import { debounce } from '$lib/template/utils/debounce';

	interface Props {
		entity: ButtonBlockEntity;
	}
	const { entity, ...props }: Props = $props();
	const uiContext = getUIContext();
	const templateContext = getTemplateContext();

	const style = $derived(stringifyCssObject(entity.style));

	const handleUpdate = debounce((editor: Editor) => {
		const coordinates = templateContext.getBlockCoordinates(entity.id);
		if (!coordinates) return;
		const command = new UpdateBlockCommand({
			store: templateContext,
			coordinates,
			updates: {
				content: {
					html: editor.getHTML(),
					json: editor.getJSON()
				}
			}
		});
		historyService.executeCommand(command, {
			type: 'block.update'
		});
	}, 300);
</script>

<a href="https://example.com" {style} onclick={(e) => e.preventDefault()} {...props}>
	{#if uiContext.selectedId === entity.id}
		<ProsemirrorEditor
			content={entity.content.json}
			extensions={buildButtonExtensions()}
			onUpdate={handleUpdate}
		/>
	{:else}
		<ProsemirrorPreview content={entity.content.html} />
	{/if}
</a>

// src/components/blocks/button/ButtonBlock.tsx
import { UpdateBlockCommand } from "@/history/commands/UpdateBlockCommand";
import type { ButtonBlockEntity } from "@/entities/template";
import { ProsemirrorEditor } from "@/richtext/adapter/components/ProsemirrorEditor";
import { ProsemirrorPreview } from "@/richtext/adapter/components/ProsemirrorPreview";
import type { Editor } from "@/richtext/core/Editor";
import { historyService } from "@/history/services/historyService";
import { useDebouncedCallback } from "@/hooks/useDebouncedCallback";
import { useCanvasStore } from "@/stores/useCanvasStore";
import { useUIStore } from "@/stores/useUIStore";

interface ButtonBlockProps {
  block: ButtonBlockEntity;
}

export const ButtonBlock: React.FC<ButtonBlockProps> = ({ block }) => {
  const selectedId = useUIStore((store) => store.selectedId);

  const template = useCanvasStore((state) => state.template);
  const setTemplate = useCanvasStore((state) => state.setTemplate);
  const getBlockCoordinates = useCanvasStore(
    (state) => state.getBlockCoordinates
  );

  const handleUpdate = useDebouncedCallback((editor: Editor) => {
    if (!template) return;
    const blockCoordinates = getBlockCoordinates(block.id);
    if (blockCoordinates === null) return;

    const command = new UpdateBlockCommand({
      ...blockCoordinates,
      template,
      setTemplate,
      type: "block.update",
      updates: {
        content: {
          html: editor.getHTML(),
          json: editor.getJSON(),
        },
      },
    });
    historyService.executeCommand(command);
  }, 300);

  return (
    <a style={block.style}>
      {selectedId === block.id ? (
        <ProsemirrorEditor
          content={block.content.json}
          onUpdate={handleUpdate}
        />
      ) : (
        <ProsemirrorPreview content={block.content.html} />
      )}
    </a>
  );
};
