// src/lib/dnd/adapter/components/DragOverlay.svelte
<script lang="ts">
	import { getDndContext } from '../contexts/dndContext.svelte';
	const { children } = $props();
	const dndContext = getDndContext();
</script>

{#if dndContext.isDragging}
	<div
		class="drag-overlay"
		style:transform="translate3d({dndContext.clientX}px, {dndContext.clientY}px, 0)"
	>
		{@render children?.()}
	</div>
{/if}

<style>
	.drag-overlay {
		position: fixed;
		top: 0;
		left: 0;
		pointer-events: none;
		z-index: 9999;
		opacity: 0.7;
	}
</style>

// src/features/dnd/adapter/components/DragOverlay.tsx
import { useDndContext } from "@/features/dnd/adapter/hooks/useDndContext";

export const DragOverlay = ({ children }: { children?: React.ReactNode }) => {
  const { state } = useDndContext();
  const { x, y } = state.coordinates;
  const isDragging = !!state.dragged;
  if (!isDragging) return null;

  return (
    <div
      className="fixed top-0 left-0 pointer-events-none z-10 opacity-70"
      style={{ transform: `translate3d(${x}px, ${y}px, 0)` }}
    >
      {children}
    </div>
  );
};
