// src/lib/richtext/adapter/components/toolbar/BasicTextStyleFormats.svelte
<script lang="ts">
	import { getRichtextContext } from '../../contexts/richtextContext.svelte';

	const prosemirrorContext = getRichtextContext();
	const editor = $derived(prosemirrorContext.activeEditor);
	const editorState = $derived.by(() => ({
		marks: {
			bold: editor?.isActive('bold'),
			italic: editor?.isActive('italic'),
			underline: editor?.isActive('underline'),
			strike: editor?.isActive('strike')
		}
	}));
</script>

<div class="container">
	<button
		onclick={() => editor?.chain().focus().toggleBold().run()}
		class:selected={editorState?.marks.bold}
		title="Bold (Ctrl+B)"
	>
		B
	</button>
	<button
		onclick={() => editor?.chain().focus().toggleItalic().run()}
		class:selected={editorState?.marks.italic}
		title="Italic (Ctrl+I)"
	>
		I
	</button>
	<button
		onclick={() => editor?.chain().focus().toggleUnderline().run()}
		class:selected={editorState?.marks.underline}
		title="Underline (Ctrl+U)"
	>
		U
	</button>
	<button
		onclick={() => editor?.chain().focus().toggleStrike().run()}
		class:selected={editorState?.marks.strike}
		title="Strikethrough"
	>
		S
	</button>
</div>

<style>
	.container {
		display: 'flex';
		flex-direction: 'row';
		gap: 4;
	}

	.selected {
		background-color: red;
	}
</style>

// src/richtext/adapter/components/toolbar/BasicTextStyleFormats.tsx
import { useProsemirror } from "@/richtext/adapter/hooks/useProsemirror";
import { useEditorState } from "@/richtext/adapter/hooks/useEditorState";

export const BasicTextStyleFormats = () => {
  const { activeEditor: editor } = useProsemirror();

  const editorState = useEditorState({
    editor,
    selector: (editor) => {
      return {
        marks: {
          bold: editor.isActive("bold"),
          italic: editor.isActive("italic"),
          strike: editor.isActive("strike"),
          underline: editor.isActive("underline"),
        },
      };
    },
  });

  if (!editor || !editorState) return null;
  
  return (
    <div style={{ display: "flex", flexDirection: "row", gap: 4 }}>
      <button
        onClick={() => editor.chain().focus().toggleBold().run()}
        style={{ backgroundColor: editorState?.marks.bold ? "red" : "" }}
        title="Bold (Ctrl+B)"
      >
        B
      </button>
      <button
        onClick={() => editor.chain().focus().toggleItalic().run()}
        style={{ backgroundColor: editorState?.marks.italic ? "red" : "" }}
        title="Italic (Ctrl+I)"
      >
        I
      </button>
      <button
        onClick={() => editor.chain().focus().toggleUnderline().run()}
        style={{ backgroundColor: editorState?.marks.underline ? "red" : "" }}
        title="Underline (Ctrl+U)"
      >
        U
      </button>
      <button
        onClick={() => editor.chain().focus().toggleStrike().run()}
        style={{ backgroundColor: editorState?.marks.strike ? "red" : "" }}
        title="Strikethrough"
      >
        S
      </button>
    </div>
  );
};
