// src/lib/richtext/adapter/components/toolbar/ClearFormats.svelte
<script lang="ts">
	import { getRichtextContext } from '../../contexts/richtextContext.svelte';

	const prosemirrorContext = getRichtextContext();
	const editor = $derived(prosemirrorContext.activeEditor);
</script>

<div class="container">
	<button onclick={() => editor?.chain().focus().unsetAllMarks().run()} title="Clear Formatting">
		CLEAR
	</button>
</div>

<style>
	.container {
		display: 'flex';
		flex-direction: 'row';
		gap: 4;
	}
</style>

// src/richtext/adapter/components/toolbar/ClearFormats.tsx
import { useProsemirror } from "@/richtext/adapter/hooks/useProsemirror";

export const ClearFormats = () => {
  const { activeEditor: editor } = useProsemirror();

  if (!editor) return null;
  
  return (
    <div style={{ display: "flex", flexDirection: "row", gap: 4 }}>
      <button
        onClick={() => editor.chain().focus().unsetAllMarks().run()}
        title="Clear Formatting"
      >
        CLEAR
      </button>
    </div>
  );
};
