// src/lib/richtext/adapter/components/toolbar/LinkFormats.svelte
<script lang="ts">
	import { getRichtextContext } from '../../contexts/richtextContext.svelte';

	const richtextContext = getRichtextContext();
</script>

<div class="container">
	<button
		onclick={() => {
			const url = window.prompt('Enter URL:');
			if (url) {
				richtextContext.activeEditor.editor?.chain().focus().setLink({ href: url }).run();
			}
		}}
		class:selected={richtextContext.activeEditor.editor?.isActive('link')}
		title="Insert Link"
	>
		LINK
	</button>

	<button
		onclick={() => richtextContext.activeEditor.editor?.chain().focus().unsetLink().run()}
		title="Remove Link"
		disabled={richtextContext.activeEditor.editor?.isActive('link')}
	>
		UNLINK
	</button>
</div>

<style>
	.container {
		display: flex;
		flex-direction: row;
		flex-wrap: wrap;
		gap: 4px;
	}

	.selected {
		background-color: red;
	}
</style>

// src/richtext/adapter/components/toolbar/LinkFormats.tsx
import type { Editor } from "@/richtext/core/Editor";
import type { ProsemirrorState } from "./ProsemirrorToolbar";

export const LinkFormats = ({
  editor,
  editorState,
}: {
  editor: Editor;
  editorState: ProsemirrorState;
}) => {
  return (
    <div style={{ display: "flex", flexDirection: "row", gap: 4 }}>
      <button
        onClick={() => {
          const url = window.prompt("Enter URL:");
          if (url) {
            editor.chain().focus().setLink({ href: url }).run();
          }
        }}
        style={{ backgroundColor: editorState?.isLink ? "red" : "" }}
        title="Insert Link"
      >
        LINK
      </button>

      <button
        onClick={() => editor.chain().focus().unsetLink().run()}
        title="Remove Link"
        disabled={editorState?.isLink}
      >
        UNLINK
      </button>
    </div>
  );
};
